version: "3"

networks:
  network:
    name: network

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - "./vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./dist:/usr/share/nginx/html"
    networks:
      - network
    depends_on:
      - app
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 1000:3306
    volumes:
      - "./app/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interiorsteel

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
    networks:
      - network
    depends_on:
      - mysql
