version: "3"

networks:
  network:
    name: network

secrets:
  db_root_password:
    file: ./db_root_password.txt

services:
  # app:
  # container_name: app
  # build:
  #   context: .
  #   dockerfile: /docker/node/Dockerfile
  # volumes:
  #   - ./dist:/usr/share/nginx/html
  # ports:
  #   - 3000:3000
  # networks:
  #   - network
  # depends_on:
  #   - mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/php:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: /usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d
    env_file:
      - ./.env.development.local
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - network
    depends_on:
      # - app
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - "./app/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: interiorsteel
    secrets:
      - db_root_password
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=100000000
    networks:
      - network
    depends_on:
      - mysql